### ISSUE TITLE
neovim+nvim-lspconfig+ruff_lsp+pyright ，ruff_lsp code action not work

### ISSUE THREAD

**Issue by hyawara** [astral-sh/ruff-lsp#360]
![image](https://github.com/astral-sh/ruff-lsp/assets/31959238/b7b7786d-2cb1-4d7c-8278-074d6e3a3156)

![image](https://github.com/astral-sh/ruff-lsp/assets/31959238/1294b940-6684-4308-a2aa-8b34decf3b48)

help me :(

**Comment by dhruvmanila** [comment]
Can you expand on what's not working? I think there are no imports to organize nor any rule which has a fix available. So, both actions should yield no results.

**Comment by hyawara** [comment]
![image](https://github.com/astral-sh/ruff-lsp/assets/31959238/747eff33-5d38-4460-96a4-441a75990aa0)

I thought it was supposed to be like this

**Comment by hyawara** [comment]
my ruff_lsp config:

![image](https://github.com/astral-sh/ruff-lsp/assets/31959238/c650b600-70a8-46cd-b55f-57373550be08)

and my pyright config:

![image](https://github.com/astral-sh/ruff-lsp/assets/31959238/d34ddc7a-cad9-4ad3-93f6-de9494dd0b72)

**Comment by dhruvmanila** [comment]
Are you expecting Ruff to _add_ the `json` import because `F821` is raised? If so, I can explain what's going on here else I'm unable to follow what you're saying.

**Comment by hyawara** [comment]
Yes, I hope so, because when I use vscode or idea, the prompt pops up and I can do that

**Comment by hyawara** [comment]
In other words, I wanted to use its import function or fix function, but it didn't work in neovim

**Comment by trag1c** [comment]
Ruff doesn't have an autofix for this violation; the prompt you see in VSCode is most likely Pylance so I believe the issue here is with pyright, not Ruff :)

**Comment by hyawara** [comment]
If this is the case, I understand ruff _ lsp wrong and need to query the pyright to deal with it

**Comment by dhruvmanila** [comment]
Not exactly. I think you might be confused here. Let me give a quick explanation about what's going on here:

There are 2 types of code actions you're seeing in Neovim - (1) is to add a `noqa` comment to disable the violation on the line where it's being raised, (2) and (3) are source level code actions. These source level code actions are _always_ shown even if they're no-op.

`ruff-lsp` is basically the LSP implementation which is to say it kinda is a layer on top of Ruff. Everything you see in your editor is coming from Ruff and can be seen when running the `ruff` CLI as well.

Now, you've a violation in your file (`F821`) and you want to run the `Fix All` code action. This code action applies fixes for all violations which has an auto-fix available. You can find this info here (https://docs.astral.sh/ruff/rules/). If the rule has the 🛠️ emoji, Ruff can fix these issues. The `F821` violation doesn't have a fix for it which is why nothing happens when  you select the "Fix All" code action.

It's recommended to use other Python language server such as Pyright with ruff-lsp as we don't provide other language features such as auto-completion, goto definition, etc. I hope this helps. Feel free to ask any other questions you might have. I'll close the issue.

@trag1c By prompts I'm assuming you mean the code actions and if so, they're coming from Ruff (prefixed by "Ruff").

**Comment by trag1c** [comment]
> they're coming from Ruff (prefixed by "Ruff").

<img width="300" alt="89343" src="https://github.com/astral-sh/ruff-lsp/assets/77130613/015f5b1c-62ab-45b8-95e8-54dd0a058781">
